services:
  - type: web
    name: app
    env: python
    buildCommand: 
      - apt-get update && apt-get install -y libportaudio2
      - pip install -r requirements.txt
    startCommand: gunicorn app:app
